name: 'Packages Split'

on:
  push:
    branches:
      - master
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # define package to repository map
        package:
          -
            local_path: 'fakeproject1'
            split_repository: 'fakeproject1'
          -
            local_path: 'fakeproject2'
            split_repository: 'fakeproject2'

    steps:
      -   uses: actions/checkout@v2

      # no tag
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "danharrin/monorepo-split-github-action@v2.3.0"
        with:
          package_directory: 'projects/${{ matrix.package.local_path }}'
          repository_organization: 'delboy1978uk'
          repository_name: '${{ matrix.package.split_repository }}'
          branch: '${{ github.ref_name }}'
          user_name: "Derek Stephen McLean"
          user_email: "delboy1978uk@gmail.com"


      # with tag
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          branch: '${{ github.ref_name }}'
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: 'projects/${{ matrix.package.local_path }}'
          repository_organization: 'delboy1978uk'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: "Derek Stephen McLean"
          user_email: "delboy1978uk@gmail.com"
