name: 'Packages Split'

on:
  push:
    branches:
      - master
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  split_testing:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3']
        package_name:
          - fakeproject1
          - fakeproject2

    name: Testing ${{ matrix.package_name }} (${{ matrix.php }})

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - run: composer install --no-progress --ansi

      # tell composer to use local package version
      - run: vendor/bin/monorepo-builder localize-composer-paths projects/${{ matrix.package_name }}/composer.json --ansi

      - working-directory: projects/${{ matrix.package_name }}
        run: ls -la data/proxies && composer update --no-progress --ansi
        env:
          COMPOSER_ROOT_VERSION: "dev-master"

      - working-directory: projects/${{ matrix.package_name }}
        run: vendor/bin/codecept run Unit

  packages_split:
    runs-on: ubuntu-latest
    needs: split_testing
    name: Split ${{ matrix.package.split_repository }}


    strategy:
      fail-fast: false
      matrix:
        # define package to repository map
        package:
          -
            local_path: 'fakeproject1'
            split_repository: 'fakeproject1'
          -
            local_path: 'fakeproject2'
            split_repository: 'fakeproject2'

    steps:
      -   uses: actions/checkout@v2

      # no tag
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "danharrin/monorepo-split-github-action@v2.3.0"
        with:
          package_directory: 'projects/${{ matrix.package.local_path }}'
          repository_organization: 'delboy1978uk'
          repository_name: '${{ matrix.package.split_repository }}'
          branch: '${{ github.ref_name }}'
          user_name: "Derek Stephen McLean"
          user_email: "delboy1978uk@gmail.com"


      # with tag
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: "danharrin/monorepo-split-github-action@v2.3.0"
        with:
          branch: '${{ github.ref_name }}'
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: 'projects/${{ matrix.package.local_path }}'
          repository_organization: 'delboy1978uk'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: "Derek Stephen McLean"
          user_email: "delboy1978uk@gmail.com"
